(TeX-add-style-hook "egbib"
 (lambda ()
    (LaTeX-add-bibitems
     "hz"
     "rayintersection"
     "lowe1999object"
     "brown2007automatic"
     "liu2010indoor"
     "chen2010indoor"
     "fischler1981random"
     "sanchez2012point"
     "kua2012loopclosure"
     "dijkstra"
     "agarwalapanoramas"
     "snavelyphototourism"
     "wangmultipleviews"
     "coorg1997matching"
     "debevechybrid"
     "debevecviewdependent"
     "bernardinimultiplescans"
     "autostitch"
     "matlabsift"
     "szeliski2006image"
     "mikolajczyk2004scale"
     "mikolajczyk2005performance"
     "ishikawa2002efficient"
     "lai1999robust"
     "lucas1981iterative"
     "hager1998efficient"
     "shum2000systems"
     "cho2003automatic"
     "yun2003comprehensive"
     "szeliski1997creating")))

