(TeX-add-style-hook "report"
 (lambda ()
    (LaTeX-add-bibitems
     "liu2010indoor"
     "lowe1999object"
     "mikolajczyk2005performance"
     "szeliski2006image"
     "chen2010indoor"
     "fischler1981random"
     "dijkstra"
     "sanchez2012point"
     "kua2012loopclosure"
     "rayintersection"
     "panorama2d"
     "autostitch"
     "openscenegraph"
     "siftgpu"
     "linebased"
     "rectangularstructures"
     "linearposeestimation"
     "hz"
     "agarwalapanoramas"
     "wangmultipleviews"
     "coorg1997matching"
     "debevechybrid"
     "bernardinimultiplescans")))

