(TeX-add-style-hook "paper"
 (lambda ()
    (LaTeX-add-bibliographies
     "report")
    (LaTeX-add-labels
     "sec:introduction"
     "fig:flowchart"
     "sec:existingApproaches"
     "fig:mosaic3D"
     "sec:simpleTextureMapping"
     "fig:projection"
     "fig:scoringFunction"
     "fig:compareAll"
     "sec:2dAlignment"
     "sec:geometryAlignment"
     "fig:geometryAlignment"
     "sec:imageOcclusion"
     "fig:occlusion"
     "sec:robustSIFTFeatureMatching"
     "sec:imageCompositing"
     "sec:mappingWithCaching"
     "fig:projectionAngles"
     "sec:shortestPath"
     "fig:dagCreation"
     "sec:blending"
     "sec:results"
     "sec:conclusion"
     "fig:results")
    (TeX-run-style-hooks
     "multirow"
     "float"
     "hyperref"
     "amssymb"
     "amsmath"
     "subfig"
     "graphicx"
     "latex2e"
     "spie10"
     "spie")))

